### ISSUE TITLE
DeviceID not found on Android10

### ISSUE THREAD

**Issue by fabclovinn** [roblav96/nativescript-telephony#15]
After using this plugin for more than a year, I'm now having issues to get the deviceID in an Android10 device.

This is the data sample I'm getting:
`callState: ""
carrierName: "T-Mobile"
countryCode: "us"
dataActivity: ""
deviceId: ""
deviceSoftwareVersion: "----"
isNetworkRoaming: ""
mcc: "310"
mnc: "260"
networkType: 13
phoneNumber: "+xxxxx"
phoneType: 1
simOperator: "310260"
simSerialNumber: ""
simState: 5
subscriberId: ""
__proto__: Object`

This is how I'm asking the data
`Telephony().then((resolved) => {
                  if (resolved.deviceId) {
                    this.logged.code = resolved.deviceId;
                    resolve();
                  } else {
                    reject();
                  }
                }).catch((error) => {
                  reject(error);
                });`

Version of plugin: 
'"nativescript-telephony": "^1.0.4",'

**Comment by fedee13** [comment]
It's not possible anymore to get deviceID on Android 10
https://developer.android.com/about/versions/10/privacy/changes#non-resettable-device-ids

**Comment by fabclovinn** [comment]
Ouch.... ok, thanks for the information.
