### ISSUE TITLE
Plugin not working with Webpack/AoT

### ISSUE THREAD

**Issue by abhayastudios** [roblav96/nativescript-telephony#3]
I just tried to bundle my project with webpack as described [here](http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html) and discovered that the telephony plugin is not working correctly, I guess due to AoT:

```
ERROR in ./pages/login.ts
Module not found: Error: Can't resolve 'nativescript-telephony' in '/Users/joni/projects/testjoni/app/pages'
 @ ./pages/login.ts 19:10-43
 @ ./app.module.ngfactory.ts
 @ ./main.aot.ts
```

Any idea what might be the issue?

**Comment by roblav96** [comment]
Not too sure. I've never used nativescript with webpack before. I'll have to look into it when I get a chance.

**Comment by abhayastudios** [comment]
I am not too familiar with it myself either, what I understand from [this explanation](https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.y0wbzesey) is that you should include the `*.metadata.json` with the plugin.
